apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-z5ts
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/quay-or-not-to-quay/nbe-e2e-wpqx-tenant/integ-app-qdlr/hacbs-test-project-z5ts@sha256:a3f2887823d6ac127c274725213de197e268c38bb0860d5543085f7bbe30f0e5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
